Repository trillek-team/tec, pull requests merged in 2021-02, with the labels that each got.

#182 Add the ability to give a computer keyboard focus and prevent controllers from acting on that input
  common/controllers/fps-controller.cpp
  common/controllers/fps-controller.hpp
  common/events.hpp
  common/simulation.cpp
  common/simulation.hpp
  common/vcomputer-system.cpp
  common/vcomputer-system.hpp
Labels: enhancement

#186 Move file factory creation into a header so it can be instantiated in both client and server
  client/CMakeLists.txt
  client/main.cpp
  common/file-factories.hpp
  common/simulation.hpp
  server/main.cpp
Labels: bug

#188 FPS mouse input, UI fixes, and Movement Netcode updates
  client/CMakeLists.txt
  client/client-game-state-queue.cpp
  client/client-game-state-queue.hpp
  client/game.cpp
  client/game.hpp
  client/gui/console.cpp
  client/gui/server-connect.cpp
  client/imgui-system.cpp
  client/imgui-system.hpp
  client/main.cpp
  client/os.cpp
  client/os.hpp
  client/server-connection.cpp
  client/server-connection.hpp
  client/voxel-volume.cpp
  common/CMakeLists.txt
  common/components/collision-body.hpp
  common/components/velocity.hpp
  common/controllers/fps-controller.cpp
  common/controllers/fps-controller.hpp
  common/event-queue.hpp
  common/events.hpp
  common/game-state-queue.cpp
  common/game-state-queue.hpp
  common/game-state.hpp
  common/physics-system.cpp
  common/physics-system.hpp
  common/proto/game_state.proto
  common/server-message.hpp
  common/server-stats.cpp
  common/server-stats.hpp
  common/simulation.cpp
  common/simulation.hpp
  common/tec-types.hpp
  common/vcomputer-system.cpp
  server/CMakeLists.txt
  server/client-connection.cpp
  server/client-connection.hpp
  server/main.cpp
  server/server-game-state-queue.cpp
  server/server-game-state-queue.hpp
Labels: feature
